name: Build and Push PHP Images

on:
  push:
    branches: [main]
    paths:
      - '8.4-fpm/Dockerfile'
      - '8.4-fpm-alpine/Dockerfile'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      build_8_4_fpm: ${{ steps.check.outputs.build_8_4_fpm }}
      build_8_4_fpm_alpine: ${{ steps.check.outputs.build_8_4_fpm_alpine }}
      build_workflow_updated: ${{ steps.check.outputs.build_workflow_updated }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Check file changes
        id: check
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} || git diff --name-only HEAD~1 HEAD)
          
          if echo "$CHANGED" | grep -q "8.4-fpm/Dockerfile"; then
            echo "build_8_4_fpm=true" >> $GITHUB_OUTPUT
          else
            echo "build_8_4_fpm=false" >> $GITHUB_OUTPUT
          fi
          
          if echo "$CHANGED" | grep -q "8.4-fpm-alpine/Dockerfile"; then
            echo "build_8_4_fpm_alpine=true" >> $GITHUB_OUTPUT
          else
            echo "build_8_4_fpm_alpine=false" >> $GITHUB_OUTPUT
          fi
          
          if echo "$CHANGED" | grep -q ".github/workflows/docker-build.yml"; then
            echo "build_workflow_updated=true" >> $GITHUB_OUTPUT
          else
            echo "build_workflow_updated=false" >> $GITHUB_OUTPUT
          fi
  
  build-8_4-fpm:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.build_8_4_fpm == 'true' || (needs.check_changes.outputs.build_workflow_updated == 'true' && github.event_name != 'workflow_dispatch') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version tag
        id: version
        run: |
          DATE=$(date +'%Y.%m.%d')
          COMMIT_SHORT=$(git rev-parse --short HEAD)
          echo "tag=${DATE}-${COMMIT_SHORT}" >> $GITHUB_OUTPUT
          echo "date=${DATE}" >> $GITHUB_OUTPUT
      
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: 8.4-fpm/Dockerfile
          push: true
          build-args: |
            USER_ID=1000
            GROUP_ID=1000
          tags: |
            dommin/php-8.4-fpm:latest
            dommin/php-8.4-fpm:${{ steps.version.outputs.date }}
            dommin/php-8.4-fpm:${{ steps.version.outputs.tag }}
  
  build-8_4-fpm-alpine:
    needs: check_changes
    if: ${{ needs.check_changes.outputs.build_8_4_fpm_alpine == 'true' || (needs.check_changes.outputs.build_workflow_updated == 'true' && github.event_name != 'workflow_dispatch') || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get version tag
        id: version
        run: |
          DATE=$(date +'%Y.%m.%d')
          COMMIT_SHORT=$(git rev-parse --short HEAD)
          echo "tag=${DATE}-${COMMIT_SHORT}" >> $GITHUB_OUTPUT
          echo "date=${DATE}" >> $GITHUB_OUTPUT
      
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: 8.4-fpm-alpine/Dockerfile
          push: true
          build-args: |
            USER_ID=1000
            GROUP_ID=1000
          tags: |
            dommin/php-8.4-fpm-alpine:latest
            dommin/php-8.4-fpm-alpine:${{ steps.version.outputs.date }}
            dommin/php-8.4-fpm-alpine:${{ steps.version.outputs.tag }}