name: Build PHP Images

on:
  push:
    branches:
      - main
    paths:
      - '*/Dockerfile'
      - '.github/workflows/docker-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [8.4-fpm, 8.4-fpm-alpine]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if directory exists
        id: check_dir
        run: |
          if [ -d "${{ matrix.php_version }}" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for changes
        id: check_changes
        if: steps.check_dir.outputs.exists == 'true'
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "^${{ matrix.php_version }}/"; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.check_dir.outputs.exists == 'true' && (steps.check_changes.outputs.changed == 'true' || github.event_name != 'push')
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: steps.check_dir.outputs.exists == 'true' && (steps.check_changes.outputs.changed == 'true' || github.event_name != 'push')
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        if: steps.check_dir.outputs.exists == 'true' && (steps.check_changes.outputs.changed == 'true' || github.event_name != 'push')
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.php_version }}/Dockerfile
          push: true
          tags: dommin/php-${{ matrix.php_version }}:latest