name: Build and Push PHP Images

on:
  push:
    branches: [main]
    paths:
      - 'docker/php/**'
      - '.github/workflows/docker-php.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: ["8.4-fpm", "8.4-fpm-alpine"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/php/${{ matrix.variant }}
          file: docker/php/${{ matrix.variant }}/Dockerfile
          push: true
          tags: |
            dommin/php-${{ matrix.variant }}:latest
            dommin/php-${{ matrix.variant }}:${{ steps.date.outputs.date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max