name: Build images

on:
  push:
    branches:
      - main

env:
  PHP_IMAGE: dommin/php-8.2:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build images
        run: docker build -t $PHP_IMAGE -f ./8.2-alpine/Dockerfile .
      - name: Install dependencies
        run: docker run --rm -t $API_IMAGE composer install --prefer-dist --no-progress --no-interaction
      - name: Push images
        run: docker push $PHP_IMAGE